language: php

php:
    - 7.1
    - 7.2
    - 7.3

sudo: false

before_script:
    - composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - mkdir -p build/logs
    - mkdir temp
    - composer outdated -D --strict
    - composer require --dev squizlabs/php_codesniffer
    - vendor/bin/phpcs src --standard=PSR2 -n
    - composer remove --dev squizlabs/php_codesniffer
    - vendor/bin/phpunit --coverage-text

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
    - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar
    - chmod +x php-coveralls.phar
    - travis_retry php php-coveralls.phar -x build/logs/clover.xml
